- Source/Meadow.Foundation/Leds/Led.cs
Pretty self explanitory, but in `Meadow.Foundation.Leds.Led` the public property `IsOn` was trying to impliment a protected setter via a protected field. This was needlessly complicating this class, as Port is already public. Changed implimentation to have `IsOn` Getter and Setter use Port.State instead, removed the protected field, added regions to the class and sorted usings.
> fixes git hub issue 11 with LED state not being set properly.

- Source/Meadow.Foundation.Peripherals/Displays.Lcd.CharacterDisplay/Driver/Displays.Lcd.CharacterDisplay/CharacterDisplay.cs
We can avoid the cost of writing blanks to the entire line on each `WriteLine` by padding the end of the string with spaces before writing it.
> update driver to avoid blanking the line before writing the new text

- Source/Meadow.Foundation.Core/Sensors/Buttons/PushButton.cs
While testing out the [code in the PushButton PR](https://github.com/WildernessLabs/Meadow.Foundation/pull/34), I noticed this inconsistent leading whitespace as part of a merge conflict for that PR branch.
> PushButton: unify whitespace

- Source/Meadow.Foundation.Core.Samples/Sensors.Rotary.RotaryEncoderWithButton_Sample/MeadowApp.cs
- Source/Meadow.Foundation.Core/Meadow.Foundation.Core.csproj
- Source/Meadow.Foundation.Core/Sensors/Buttons/PushButton.cs
- Source/Meadow.Foundation.Core/Sensors/Rotary/RotaryEncoder.cs
- Source/Meadow.Foundation.Core/Sensors/Rotary/RotaryEncoderWithButton.cs
This address issue #70  and also improves the logic within the RotaryEncoder class. Incorporated the fix in Pull Request #34 to address the button firing opposite events. 
The major change to the RotaryEncoder was to monitor the events separately. The previous logic was not handling bad digital events properly and could leave no values incrementing. This version still has issues with handling speed of rotation (rotation direction does get missed) however, it does not flag on improper clock events. I also significantly reduced the denounce as the new software logic allows for a lot faster readings. It will still glitch if you turn it to rapidly but will recover now (previously it would not)
Better ways to address the button issue or the events triggering are always welcome! The same demo …
> Fix rotation rotary encoder with button

- Source/Meadow.Foundation.Core/Sensors/Temperature/AnalogTemperatureSensor.cs
In VoltageToTemperature method yAdjusted value will be in millivolts.
The calculation to convert millivolts to temperature does not require multiplying by 1000.
> Remove second multiplication by 1000

- Source/Meadow.Foundation.Core/Color.cs
- Source/Meadow.Foundation.Core/Leds/Led.cs
- Source/Meadow.Foundation.Core/Leds/LedBarGraph.cs
- Source/Meadow.Foundation.Core/Leds/PwmLed.cs
- Source/Meadow.Foundation.Core/Leds/PwmLedBarGraph.cs
- Source/Meadow.Foundation.Core/Leds/RgbLed.cs
- Source/Meadow.Foundation.Core/Leds/RgbPwmLed.cs
To minimize API breaking changes over changing uint parameters to int in Meadow.Foundation.Core, added obsolete tags on old methods to deprecate them and remove them in future updates.
> Add obsolete methods for API changes

- Source/Meadow.Foundation.Peripherals/Sensors.Atmospheric.Bme280/Samples/Sensors.Atmospheric.Bme280_Sample/MeadowApp.cs
It looks like the filter evolved from temp-only to temp and humidity. This just updates the various comments to align with that.
> [BME280] Clarify observer filter comments

- Source/Meadow.Foundation.Libraries_and_Frameworks/Displays.TextDisplayMenu/Driver/BaseClasses/MenuItemBase.cs
{Fixes #381}
I'm not sure if this has other implications around sub-menus, but it does fix the issue I was seeing with single-item sub-menu pages.
> [TextDisplayMenu] Allow sub-menu of 1 item

- Source/Meadow.Foundation.Libraries_and_Frameworks/Displays.TextDisplayMenu/Driver/BaseClasses/MenuItemBase.cs
Reverts WildernessLabs/Meadow.Foundation#382
Accidentally targeted `main` instead of `develop`.
> Revert "[TextDisplayMenu] Allow sub-menu of 1 item"

- Source/Meadow.Foundation.Libraries_and_Frameworks/Displays.TextDisplayMenu/Driver/BaseClasses/MenuItemBase.cs
If you have a menu with a single sub-item, it will not be recognized as a sub-menu. Selecting the resulting menu item it will neither trigger `Selected` nor open a sub-menu.
```csharp
var menuItems = new MenuItem[]
{
...
new MenuItem("Options", subItems: new MenuItem[]
{
new MenuItem($"Version {version}"),
}),
};
```
> [TextDisplayMenu] Cannot have sub-menu of 1 item

- Source/Meadow.Foundation.Peripherals/Sensors.Temperature.Thermistor/Driver/Thermistor.cs
While still not ideal yet, since line breaks are not preserved, this at least gets the remark XML to show up.
Also, it fixes an XML build warning.
Before:
After:
So many attempts to get this to render correctly have failed. They either don't add line breaks or don't add the leading whitespace. For example, this simple version _should_ do both but doesn't. (And adding a `CDATA` to each individual line also doesn't work.)
```csharp
/// <![CDATA[
/// 3.3V >-----[ 10k R ]---+-------------< Analog_in
///                        |
///                        +---[ TM ]--- < GND
/// ]]>
```
> Fix XML error to show remarks in Intellisense tip

- Source/Meadow.Foundation.Core.Samples/Audio.PiezoSpeaker_Sample/.vscode/launch.json
- Source/Meadow.Foundation.Core.Samples/Generators.SoftPwmPort_Sample/.vscode/launch.json
- Source/Meadow.Foundation.Core.Samples/Leds.LedBarGraph_Sample/.vscode/launch.json
- Source/Meadow.Foundation.Core.Samples/Leds.Led_Sample/.vscode/launch.json
- Source/Meadow.Foundation.Core.Samples/Leds.PwmLedBarGraph_Sample/.vscode/launch.json
- Source/Meadow.Foundation.Core.Samples/Leds.PwmLed_Onboard_Sample/.vscode/launch.json
- Source/Meadow.Foundation.Core.Samples/Leds.PwmLed_Sample/.vscode/launch.json
- Source/Meadow.Foundation.Core.Samples/Leds.RgbLed_Sample/.vscode/launch.json
- Source/Meadow.Foundation.Core.Samples/Leds.RgbPwmLed_Onboard_Sample/.vscode/launch.json
- Source/Meadow.Foundation.Core.Samples/Leds.RgbPwmLed_Sample/.vscode/launch.json
- Source/Meadow.Foundation.Core.Samples/Motor.HBridgeMotor_Sample/.vscode/launch.json
- Source/Meadow.Foundation.Core.Samples/Relays.Relay_Sample/.vscode/launch.json
- Source/Meadow.Foundation.Core.Samples/Sensors.Buttons.PushButton_BasicSample/.vscode/launch.json
- Source/Meadow.Foundation.Core.Samples/Sensors.Buttons.PushButton_Sample/.vscode/launch.json
- Source/Meadow.Foundation.Core.Samples/Sensors.Environmental.AnalogWaterLevel_Sample/.vscode/launch.json
- Source/Meadow.Foundation.Core.Samples/Sensors.HID.AnalogJoystick_Sample/.vscode/launch.json
- Source/Meadow.Foundation.Core.Samples/Sensors.HallEffect_Sample/.vscode/launch.json
- Source/Meadow.Foundation.Core.Samples/Sensors.Light.AnalogLightSensor_Sample/.vscode/launch.json
- Source/Meadow.Foundation.Core.Samples/Sensors.Rotary.RotaryEncoderWithButton_Sample/.vscode/launch.json
- Source/Meadow.Foundation.Core.Samples/Sensors.Rotary.RotaryEncoder_Sample/.vscode/launch.json
- Source/Meadow.Foundation.Core.Samples/Sensors.Switches.DipSwitch_Sample/.vscode/launch.json
- Source/Meadow.Foundation.Core.Samples/Sensors.Switches.SpdtSwitch_Sample/.vscode/launch.json
- Source/Meadow.Foundation.Core.Samples/Sensors.Switches.SpstSwitch_Sample/.vscode/launch.json
- Source/Meadow.Foundation.Core.Samples/Sensors.Temperature.AnalogTemperature_Sample/.vscode/launch.json
Part of WildernessLabs/Meadow_Issues#236.
The addition of the `.vscode` folder doesn't appear to impact VS2022 users at all, even with several folders present in a solution.  I confirmed expected debug behavior using only the Blinky C# project, but it worked as expected.
> Add launch.config to sample projects for VSCode users

- .github/ISSUE_TEMPLATE/bug_report.md
Initial bug report and feature request templates to make sure we are getting as much useful information as possible. I customized the samples as best as I could for Meadow in the [template proposal on Meadow_Issues](https://github.com/WildernessLabs/Meadow_Issues/pull/233) to help track down version or hardware-specific issues. Then, for this one, I just added a **Meadow.Foundation** section.
If there are other things from the user that could help, let me know (or add them directly).
> Add initial issue template

- Source/Meadow.Foundation.Peripherals/Displays.TftSpi/Driver/Drivers/Gc9a01.cs
- Source/Meadow.Foundation.Peripherals/Displays.TftSpi/Driver/Drivers/Hx8357d.cs
- Source/Meadow.Foundation.Peripherals/Displays.TftSpi/Driver/Drivers/Ili9163.cs
- Source/Meadow.Foundation.Peripherals/Displays.TftSpi/Driver/Drivers/Ili9341.cs
- Source/Meadow.Foundation.Peripherals/Displays.TftSpi/Driver/Drivers/Ili9481.cs
- Source/Meadow.Foundation.Peripherals/Displays.TftSpi/Driver/Drivers/Ili9486.cs
- Source/Meadow.Foundation.Peripherals/Displays.TftSpi/Driver/Drivers/Ili9488.cs
- Source/Meadow.Foundation.Peripherals/Displays.TftSpi/Driver/Drivers/Rm68140.cs
- Source/Meadow.Foundation.Peripherals/Displays.TftSpi/Driver/Drivers/S6D02A1.cs
- Source/Meadow.Foundation.Peripherals/Displays.TftSpi/Driver/Drivers/Ssd1331.cs
- Source/Meadow.Foundation.Peripherals/Displays.TftSpi/Driver/Drivers/St7735.cs
- Source/Meadow.Foundation.Peripherals/Displays.TftSpi/Driver/Drivers/St7789.cs
- Source/Meadow.Foundation.Peripherals/Displays.TftSpi/Driver/Drivers/St7796s.cs
- Source/Meadow.Foundation.Peripherals/Displays.TftSpi/Driver/TftSpiBase.cs
The `SetAddressWindow()` function sends data for caset and raset commands one byte at a time. This causes a loss of performance due to the overhead of loading each individual byte to the SPI bus one at a time.  
Combining these 4 bytes into 1 SPI call brings the SetWindowAddress timing to go from ~5ms to 2ms.
This PR also moves the logic of `SetWindowAddress()` into the `TftSpiBase` base class, since most displays re-use them.
> TftSpiBase.SetAddressWindow optimizations

- Source/Meadow.Foundation.Libraries_and_Frameworks/Displays.TextDisplayMenu/Driver/TextDisplayMenu.cs
Noticed in [Clima Hack Kit](https://github.com/WildernessLabs/Clima/tree/develop/Source/Additional%20Samples/Clima_HackKit_Demo) sample, the item selected indicator (*) was being drawn outside of the screen on the ST7789 display due to selecting a Factor Scale of 2, so it was not taken in consideration when calculating the number of ` ` for the padding between the item element and the selected (*) symbol.
> Fix space padding when showing * or > indicators

- Source/Meadow.Foundation.Libraries_and_Frameworks/Graphics.MicroGraphics/Driver/MicroGraphics.cs
Had a crash when a sprite animated off the top of the screen. Found this `x` where a `y` probably should be. Changing it fixed the issue for my code.
> MicroGraphics: Fix typo for y out-of-bounds check

- Source/Meadow.Foundation.Peripherals/Sensors.Atmospheric.Bme68x/Driver/Bme68x.cs
Masking CTRL_GAS_1 for Bme68x in HeaterProfile
The mask should allow to set nb_conv<3:0> bits as per datasheet.
From BME688 datasheet:
However, for BME688 it seems I have to read the values from different registers compared to 680.
And also the gas resistance calculation seems to be different too:
```csharp
Resistance CalculateGasResistance_BME688(ushort adcGasRes, byte gasRange)
{
if (calibration == null) throw new NullReferenceException("Calibration must be defined");
var var1 = ((uint)262144) >> gasRange;
var var2 = ((int)adcGasRes) - 512;
var2 *= 3;
var2 = 4096 + var2;
var gasResistance = 1000000.0 * var1 / var2;
return new Resistance(gasResistance, Resistance.UnitType.Ohms);
```
Registers are different too:
```csharp
GAS_RES = 0x2C,
GAS_RANGE = 0x2D,
```
And GasConversionIsEnabled …
> Masking CTRL_GAS_1 for Bme68x in HeaterProfile

- Source/Meadow.Foundation.Peripherals/ICs.IOExpanders.Pcx857x/Driver/Drivers/Extras/Pcx8574.cs
An array with a length of 1 cannot be accessed at index 1 but only at 0.
> Bugfix: Array indexing at non existent item

- Source/Meadow.Foundation.Libraries_and_Frameworks/Graphics.MicroLayout/Driver/Controls/GradientBox.cs
- Source/Meadow.Foundation.Libraries_and_Frameworks/Graphics.MicroLayout/Driver/DisplayTheme.cs
Wanted to add Gradient background for HMI screens, so added this GradientBox control.  For this to work, it has 3 important fields:
- `isHoritzontal` - Its assigning the direction of the gradient. Horizontal is default if not assigned by user.
- `StartColor` - Its assigning a color for the Left or Top depending if gradient orientation is horizontal or vertical
- `EndColor` - Its assigning a color for the Right or Bottom depending if gradient orientation is horizontal or vertical
For example, this code generates the following background:
```csharp
DisplayScreen.Controls.Add(new GradientBox(0, 0, display.Width, display.Height)
{
StartColor = Meadow.Color.FromHex("#5AC0EA"),
EndColor = Meadow.Color.FromHex("#B8E4F6")
});
```
> Add GradientBox control

- Source/Meadow.Foundation.Libraries_and_Frameworks/Sensors.Location.Gnss.NmeaProcessor/Driver/NmeaProcessor.cs
Normally id like internal outputs from drivers in the Trace level to keep Info level clean for the user.
> Tuck log output to trace

- Source/Meadow.Foundation.Libraries_and_Frameworks/Serialization.MicroJson/Driver/MicroJson.cs
**Summary**
As mentioned in [a private slack discussion](https://wildernesslabs.slack.com/archives/C05TXSF4B8E/p1716246927429179), the `Resolver.JsonSerializer.Serialize` in the `MeadowCloudConnectionService` doesn't seem to properly serialize some JSONs. 
So, this PR aims to escape special characters like double quotes ("), backslashes (\), newlines (\n), carriage returns (\r), tabs (\t), backspaces (\b), and form feeds (\f) to ensure that the resulting JSON string is valid and can be properly parsed by a JSON parser.
> Escapes special characters in a string to ensure it is JSON-compliant

- Source/Meadow.Foundation.Peripherals/Displays.Silk/Driver/SkiaPixelBuffer.cs
WriteBuffer optimization expects the buffer types to match not the actual format of the pixels. To take advantage of the optimization you should  be able to create matching buffer type.
> Make SkiaPixelBuffer public

- Source/Meadow.Foundation.Core/Communications/SpiCommunications.cs
This has many dependencies that need to be verified before merging.  Any driver calling the `byte ReadRegister(byte)` overload needs to be verified.
> READ THE DESCIPTION BEFORE MERGE! bug fix in SpiComms.ReadRegister

- Source/Meadow.Foundation.Peripherals/ICs.IOExpanders.Sc16is7x2/Driver/Sc16is7x2.Sc16is7x2Channel.cs
Currently if you try to call 
`port.Parity = Parity.Even;`
before first calling 
`port.DataBits = 8;`
the application will crash as `_dataBits` have not been set locally when initialised. `StopBits` is the same.
> Exception altering Parity before setting DataBits

- Source/Meadow.Foundation.Peripherals/Sensors.Weather.SwitchingAnemometer/Driver/SwitchingAnemometer.cs
- Source/Meadow.Foundation.Peripherals/Sensors.Weather.SwitchingAnemometer/Samples/SwitchingAnemometer_Sample/MeadowApp.cs
***Driver***
Use the Delta property of the observed DigitalPortResult to determine interval from one edge to the next. 
Ignore impossibly high speeds set by new property MaxSpeed, defaults to 500 km/hr.
Minor code refactor to make code execution clearer that speed returned is zero if to much time between samples, to few samples, or speed is too high.
Add clarification <remarks> to some comments
***Sample***
Added commented code for testing the SwitchingAnemometer by driving the input from a PWM port running at set frequency.
> Fix speed calculation in SwitchingAnemometer

- Source/Meadow.Foundation.Peripherals/Displays.TftSpi/Driver/Drivers/St7789.cs
- Source/Meadow.Foundation.Peripherals/Displays.TftSpi/Driver/TftSpiBase.cs
- Source/Meadow.Foundation.Peripherals/ICs.IOExpanders.Ftxxxx/Samples/Ft232h_Sample/Ft232h_Sample.csproj
- Source/Meadow.Foundation.Peripherals/ICs.IOExpanders.Ftxxxx/Samples/Ft232h_Sample/Program.cs
Fix for https://github.com/WildernessLabs/Meadow_Issues/issues/826
Also changed API for ST7789 to have the reset pin optional (nullable) (it is optional when driving the display, so it should be nullable IMO)
> Change TftSpiBase displays to use SpiBus.Write instead of Exchange
