Source/Meadow.Foundation.sln
Hoping to avoid any loading errors when folks first open the solution.
=> Remove Meadow.Core project from solution

Source/Peripheral_Libs/Displays.LCD.CharacterDisplay/CharacterDisplay.cs
Fix for Issue #17
https://github.com/WildernessLabs/Meadow.Foundation/issues/17
Added the Initialize that was missing from the constructor.
=> Added Initialize to constructor

Source/Meadow.Foundation.Libraries_and_Frameworks/Displays.GraphicsLibrary/GraphicsLibrary.cs
Added Height and Width properties for Issue #30
=> Add height and width properties

Source/Meadow.Foundation.Peripherals/Displays.Max7219/Driver/Displays.Max7219/Displays.Max7219.csproj
=> beta publish test

Source/Meadow.Foundation.Core.Samples/Leds.RgbPwmLed_Sample/MeadowApp.cs, Source/Meadow.Foundation.Core/Leds/RgbPwmLed.cs
The method was already in the driver, but was protected, so I made it public and clean the code a bit.
=> Add brightness parameter for the SetColor method

Source/Meadow.Foundation.Core/Sensors/Buttons/PushButton.cs
- Do not raise click for long press
- Turn off long press by default
=> push button long press change

Source/Meadow.Foundation.Peripherals/Sensors.Radio.Rfid.IDxxLA/Driver/Sensors.Radio.Rfid.IDxxLA/IDxxLA.cs, Source/Meadow.Foundation.Peripherals/Sensors.Radio.Rfid.IDxxLA/Driver/Sensors.Radio.Rfid.IDxxLA/Sensors.Radio.Rfid.IDxxLA.csproj, Source/Meadow.Foundation.Peripherals/Sensors.Radio.Rfid.IDxxLA/Samples/Sensors.Radio.Rfid.IDxxLA_Sample/MeadowApp.cs, Source/Meadow.Foundation.Peripherals/Sensors.Radio.Rfid.IDxxLA/Samples/Sensors.Radio.Rfid.IDxxLA_Sample/Program.cs
None of these are breaking
- Fixed namespacing of sample project
- Fixed a double assignment of `LastRead`
=> IDxxLA fixes

Source/Meadow.Foundation.Core/Leds/Led.cs, Source/Meadow.Foundation.Core/Leds/LedBarGraph.cs, Source/Meadow.Foundation.Core/Leds/PwmLed.cs, Source/Meadow.Foundation.Core/Leds/PwmLedBarGraph.cs, Source/Meadow.Foundation.Core/Leds/RgbLed.Enums.cs, Source/Meadow.Foundation.Core/Leds/RgbLed.cs, Source/Meadow.Foundation.Core/Leds/RgbPwmLed.cs
I did an update to Led, PwmLed, RgbLed and RgbPwmLed where
- Each driver has an IsOn boolean property to easily turn on or off the LED (RGB LEDs will just turn on based on the current color set, initialized in White)
- I consolidated all the animations methods to use Task with Cancellable Token sources
- Added Summary to all public methods and properties
- Consolidated all default parameter values for animations such as StartPulse across all drivers
- Removed code region sections
=> Leds update

Source/Meadow.Foundation.Libraries_and_Frameworks/DataLoggers.AdafruitIO/AdafruitIO.cs
AdafruitIO only permits web API Post request to have a single value and "created_at" time stamp so that has been changed so that for instance to post and array of SensorReading requires multiple PostAsync calls. The feed name is a component of the URI., so that is now corrected to the form http://io.adafruit.com/api/v2/{UserName}/feeds/{Group}.{FeedKey}/data
Included the "group" key as an optional parameter now. If it is left out then the data will be posted to the default group.
This class now uses the HttpClient class and it's PostAsync method.
This change to the DataLoggers.AdafruitIO class is required for my pending upgrade to the Clima Solution that allows it to use this logger.
I have not bumped the DataLoggers version.
=> Updated to correct API URI form and Json data form and use HttpClient.PostAsync

Source/Meadow.Foundation.Libraries_and_Frameworks/Graphics/MicroGraphics/Driver/Graphics.MicroGraphics/GraphicsPath.cs, Source/Meadow.Foundation.Libraries_and_Frameworks/Graphics/MicroGraphics/Driver/Graphics.MicroGraphics/IsExternalInit.cs, Source/Meadow.Foundation.Libraries_and_Frameworks/Graphics/MicroGraphics/Driver/Graphics.MicroGraphics/MicroGraphics.GraphicsPath.cs, Source/Meadow.Foundation.Libraries_and_Frameworks/Graphics/MicroGraphics/Driver/Graphics.MicroGraphics/MicroGraphics.TextDisplay.cs, Source/Meadow.Foundation.Libraries_and_Frameworks/Graphics/MicroGraphics/Driver/Graphics.MicroGraphics/MicroGraphics.cs, Source/Meadow.Foundation.Libraries_and_Frameworks/Graphics/MicroGraphics/Driver/Graphics.MicroGraphics/Path.cs, Source/Meadow.Foundation.Libraries_and_Frameworks/Graphics/MicroGraphics/Driver/Graphics.MicroGraphics/Point.cs, Source/Meadow.Foundation.Libraries_and_Frameworks/Graphics/MicroGraphics/Driver/Graphics.MicroGraphics/Rect.cs, Source/Meadow.Foundation.Libraries_and_Frameworks/Graphics/MicroGraphics/Driver/Graphics.MicroGraphics/Size.cs, Source/Meadow.Foundation.Peripherals/Displays.TftSpi/Driver/Displays.TftSpi/TftSpiBase.cs, Source/Meadow.Foundation.Peripherals/Displays.TftSpi/Samples/Displays.TftSpi.ST7789_Sample/MeadowApp.cs
Tracking additions to add basic support for drawing paths in MicroGraphics
=> Feature: Path (don't merge)

Source/Meadow.Foundation.Peripherals/Sensors.Light.Tsl2591/Driver/Sensors.Light.TSL2591/TSL2591.cs
Added multiple properties to the TSL2591 object:
* Lux
* Visible light
* Infrared
* Gain
* Integration time
* Full spectrum (Visible light and IR combined)
=> Extend tsl2591 functionality

Source/Meadow.Foundation.Peripherals/Sensors.Moisture.Capacitive/Driver/Sensors.Moisture.Capacitive/Capacitive.cs, Source/Meadow.Foundation.Peripherals/Sensors.Moisture.Capacitive/Samples/Sensors.Moisture.Capacitive_Sample/MeadowApp.cs
Update for Capacitive soil moisture sensor so Read() returns a FloatChangeResult type instead of a float
=> Capacitive Soil Moisture sensor update

Source/Meadow.Foundation.Core.Samples/Leds.LedBarGraph_Sample/MeadowApp.cs, Source/Meadow.Foundation.Core.Samples/Leds.Led_Sample/MeadowApp.cs, Source/Meadow.Foundation.Core.Samples/Leds.PwmLedBarGraph_Sample/MeadowApp.cs, Source/Meadow.Foundation.Core.Samples/Leds.PwmLed_Sample/MeadowApp.cs, Source/Meadow.Foundation.Core.Samples/Leds.RgbLed_Sample/MeadowApp.cs, Source/Meadow.Foundation.Core.Samples/Leds.RgbPwmLed_Onboard_Sample/MeadowApp.cs, Source/Meadow.Foundation.Core.Samples/Leds.RgbPwmLed_Sample/MeadowApp.cs, Source/Meadow.Foundation.Core.Samples/Sensors.Buttons.PushButton_BasicSample/MeadowApp.cs, Source/Meadow.Foundation.Core/Leds/Helpers.cs, Source/Meadow.Foundation.Core/Leds/Led.cs, Source/Meadow.Foundation.Core/Leds/LedBarGraph.cs, Source/Meadow.Foundation.Core/Leds/PwmLed.cs, Source/Meadow.Foundation.Core/Leds/PwmLedBarGraph.cs, Source/Meadow.Foundation.Core/Leds/RgbLed.cs, Source/Meadow.Foundation.Core/Leds/RgbPwmLed.cs, Source/Meadow.Foundation.Core/Leds/TypicalForwardVoltage.cs, Source/Meadow.Foundation.Libraries_and_Frameworks/Displays.TextDisplayMenu/Samples/TextDisplayMenu_GameMenu_Sample/MeadowApp.cs, Source/Meadow.Foundation.Libraries_and_Frameworks/Displays.TextDisplayMenu/Samples/TextDisplayMenu_Sample/MeadowApp.cs, Source/Meadow.Foundation.Peripherals/Sensors.Weather.SwitchingAnemometer/Samples/SwitchingAnemometer_Sample/MeadowApp.cs
https://github.com/WildernessLabs/Meadow.Foundation/issues/301
=> GH-301 Unitize LEDs forward voltages

Source/Meadow.Foundation.Libraries_and_Frameworks/DataLoggers.ThingSpeak/Driver/DataLoggers.ThingSpeak.csproj
=> Fix ThingSpeak package ID

Source/Meadow.Foundation.Core.Samples/Sensors.Environmental.AnalogWaterLevel_Sample/MeadowApp.cs, Source/Meadow.Foundation.Peripherals/Sensors.Light.Alspt19315C/Samples/Alspt19315C_Sample/MeadowApp.cs, Source/Meadow.Foundation.Peripherals/Sensors.Light.Bh1745/Samples/Bh1745_Sample/MeadowApp.cs, Source/Meadow.Foundation.Peripherals/Sensors.Light.Bh1750/Samples/Bh1750_Sample/MeadowApp.cs, Source/Meadow.Foundation.Peripherals/Sensors.Light.Max44009/Samples/Max44009_Sample/MeadowApp.cs, Source/Meadow.Foundation.Peripherals/Sensors.Light.Si1145/Samples/Si1145_Sample/MeadowApp.cs, Source/Meadow.Foundation.Peripherals/Sensors.Light.Tcs3472x/Samples/Tcs3472x_Sample/MeadowApp.cs, Source/Meadow.Foundation.Peripherals/Sensors.Light.Temt6000/Samples/Temt6000_Sample/MeadowApp.cs, Source/Meadow.Foundation.Peripherals/Sensors.Light.Tsl2591/Samples/Tsl2591_Sample/MeadowApp.cs, Source/Meadow.Foundation.Peripherals/Sensors.Light.Veml7700/Samples/Veml7700_Sample/MeadowApp.cs, Source/Meadow.Foundation.Peripherals/Sensors.Motion.Adxl3xx/Samples/Adxl335_Sample/MeadowApp.cs, Source/Meadow.Foundation.Peripherals/Sensors.Motion.Adxl3xx/Samples/Adxl337_Sample/MeadowApp.cs, Source/Meadow.Foundation.Peripherals/Sensors.Motion.Adxl3xx/Samples/Adxl345_Sample/MeadowApp.cs, Source/Meadow.Foundation.Peripherals/Sensors.Motion.Adxl3xx/Samples/Adxl362_Sample/MeadowApp.cs, Source/Meadow.Foundation.Peripherals/Sensors.Motion.Adxl3xx/Samples/Adxl377_Sample/MeadowApp.cs, Source/Meadow.Foundation.Peripherals/Sensors.Motion.Apds9960/Samples/Apds9960_Sample/MeadowApp.cs, Source/Meadow.Foundation.Peripherals/Sensors.Motion.Bno055/Samples/Bno055_Sample/MeadowApp.cs, Source/Meadow.Foundation.Peripherals/Sensors.Motion.Hmc5883/Samples/Hmc5883_Sample/MeadowApp.cs, Source/Meadow.Foundation.Peripherals/Sensors.Motion.Hmc5883/Samples/Qmc5883_Sample/Qmc5883_Sample/MeadowApp.cs, Source/Meadow.Foundation.Peripherals/Sensors.Motion.Mag3110/Samples/Mag3110_Sample/MeadowApp.cs, Source/Meadow.Foundation.Peripherals/Sensors.Motion.Mma7660fc/Samples/Mma7660fc_Sample/MeadowApp.cs, Source/Meadow.Foundation.Peripherals/Sensors.Motion.Mpu6050/Samples/Mpu6050_Sample/MeadowApp.cs
Just saw this while working on a new device driver. Looks like it might have been copy-pasted around a bit.
=> Fix IObservable typo

Source/Meadow.Foundation.Peripherals/ICs.IOExpanders.Mcp23x08/Driver/ICs.IOExpanders.Mcp23x08/Mcp23x08.IMcpDeviceComms.cs, Source/Meadow.Foundation.Peripherals/ICs.IOExpanders.Mcp23x08/Driver/ICs.IOExpanders.Mcp23x08/Mcp23x08.cs
Reworked the MCP23x08 constructor to remove the raised NotImplementedException
=> Issues 311

Source/Meadow.Foundation.Libraries_and_Frameworks/Graphics/MicroGraphics/Driver/Graphics.MicroGraphics/Image.cs
fixes https://github.com/WildernessLabs/Meadow.Foundation/issues/331
Detailed notes and demonstration of fix in the issue above.
=> Fixes bitmap padding corruption

Source/Meadow.Foundation.Peripherals/ICs.IOExpanders.Mcp23xxx/Driver/Mcp23xxx.Registers.cs, Source/Meadow.Foundation.Peripherals/ICs.IOExpanders.Mcp23xxx/Driver/Mcp23xxx.cs
=> potential fix for MCP interrupts

Source/Meadow.Foundation.Core/Leds/RgbPwmLed.cs
Fix for https://github.com/WildernessLabs/Meadow_Issues/issues/279
=> RgbPwmLed PulseDuration fix

Source/Meadow.Foundation.Peripherals/Sensors.Temperature.Thermistor/Driver/SteinhartHartCalculatedThermistor.cs
This is causing excess noise in the logs, removing.
=> Remove extra logging in SteinhartHartCalculatedThermistor

Source/Meadow.Foundation.Libraries_and_Frameworks/Graphics.MicroLayout/Driver/DisplayScreen.cs
=> Fix XML comment typo

Source/Meadow.Foundation.Libraries_and_Frameworks/Displays.TextDisplayMenu/Driver/InputTypes/InputType.cs, Source/Meadow.Foundation.Libraries_and_Frameworks/Displays.TextDisplayMenu/Driver/TextDisplayMenu.cs, Source/Meadow.Foundation.Libraries_and_Frameworks/Displays.TextDisplayMenu/Samples/TextDisplayMenuTft_Sample/MeadowApp.cs, Source/Meadow.Foundation.Libraries_and_Frameworks/Displays.TextDisplayMenu/Samples/TextDisplayMenuTft_Sample/TextDisplayMenuTft_Sample.csproj, Source/Meadow.Foundation.Libraries_and_Frameworks/Displays.TextDisplayMenu/Samples/TextDisplayMenuTft_Sample/meadow.config.yaml, Source/Meadow.Foundation.Libraries_and_Frameworks/Displays.TextDisplayMenu/Samples/TextDisplayMenuTft_Sample/menu.json, Source/Meadow.Foundation.sln
=> TextSisplayMenu OnOff fix

Source/Meadow.Foundation.Core/Relays/Relay.cs
Add code to raise event when relay changed
=> add event on relay change

Source/Meadow.Foundation.Libraries_and_Frameworks/Graphics.MicroLayout/Driver/Charts/LineChart.cs, Source/Meadow.Foundation.Libraries_and_Frameworks/Graphics.MicroLayout/Driver/Charts/LineChartSeriesCollection.cs, Source/Meadow.Foundation.Libraries_and_Frameworks/Graphics.MicroLayout/Driver/Charts/LineSeriesPointCollection.cs
- Fix Min/Max values
- Add Remove/ClearAll capabilities for Points and Series Collections
- LineChart will now draw within x,y,width,height bounds
- Y axis will re-arrange automatically based on the Y Labels
- X axis trimmed to not overlap min y value
=> Microlayout updates

Source/Meadow.Foundation.Core/Leds/PwmLed.Animations.cs, Source/Meadow.Foundation.Core/Leds/PwmLed.cs
see this [slack thread](https://wildernesslabspublic.slack.com/archives/CQWD660E8/p1709612201388229) for context
=> Making PwmLed pulses smoother, fixing brightness spikes

Source/Meadow.Foundation.Peripherals/ICs.ADC.Ads1x15/Driver/Ads1x15Base.Enums.cs, Source/Meadow.Foundation.Peripherals/ICs.IOExpanders.Sc16is7x2/Driver/FifoBuffer.cs, Source/Meadow.Foundation.Peripherals/ICs.IOExpanders.Sc16is7x2/Driver/Sc16is7x2.Enums.cs, Source/Meadow.Foundation.Peripherals/ICs.IOExpanders.Sc16is7x2/Driver/Sc16is7x2.I2c.cs, Source/Meadow.Foundation.Peripherals/ICs.IOExpanders.Sc16is7x2/Driver/Sc16is7x2.Sc16is7x2Channel.cs, Source/Meadow.Foundation.Peripherals/ICs.IOExpanders.Sc16is7x2/Driver/Sc16is7x2.Spi.cs, Source/Meadow.Foundation.Peripherals/ICs.IOExpanders.Sc16is7x2/Driver/Sc16is7x2.cs
This is an insignificant change, but I have to practice a bit before I create PRs for some drivers (MCP23xxx and SC16IS7x2). I have done it before, but it's too long ago to remember.
=> Better description for the gain options.

Source/Meadow.Foundation.Peripherals/ICs.ADC.Ads1x15/Driver/Ads1x15Base.Enums.cs, Source/Meadow.Foundation.Peripherals/ICs.IOExpanders.Sc16is7x2/Driver/FifoBuffer.cs, Source/Meadow.Foundation.Peripherals/ICs.IOExpanders.Sc16is7x2/Driver/Sc16is7x2.Enums.cs, Source/Meadow.Foundation.Peripherals/ICs.IOExpanders.Sc16is7x2/Driver/Sc16is7x2.I2c.cs, Source/Meadow.Foundation.Peripherals/ICs.IOExpanders.Sc16is7x2/Driver/Sc16is7x2.Sc16is7x2Channel.cs, Source/Meadow.Foundation.Peripherals/ICs.IOExpanders.Sc16is7x2/Driver/Sc16is7x2.Spi.cs, Source/Meadow.Foundation.Peripherals/ICs.IOExpanders.Sc16is7x2/Driver/Sc16is7x2.cs
Some bug fixes and several improvements and optimizations. Also moved code between classes. This makes the code easier to read and reduce calls between classes.
=> Sc16is7x2 bugfix

Source/Meadow.Foundation.Peripherals/ICs.IOExpanders.Ftxxxx/Driver/FtdiExpander.Ft232hSpiBus.cs, Source/Meadow.Foundation.Peripherals/ICs.IOExpanders.Ftxxxx/Samples/Ft232h_Sample/Ft232h_Sample.csproj, Source/Meadow.Foundation.Peripherals/ICs.IOExpanders.Ftxxxx/Samples/Ft232h_Sample/Program.cs, Source/Meadow.Foundation.Peripherals/ICs.IOExpanders.Ftxxxx/Tests/FT232.Unit.Tests/Ftd2xxTests.cs
(cherry picked from commit 1f257a24ad6c83762d2b62b7a531056b2b63568d)
=> ft232h SPI fixes

Source/Meadow.Foundation.Libraries_and_Frameworks/Graphics.MicroGraphics/Driver/MicroGraphics.cs
for displays that don't internally handle rotation
=> Add partial Show support to MicroGraphics
